In [1]:
import pandas as pd
df = pd.read_parquet("PortfoliosOutcomePlusDiff_arne.parquet")
df

,date,bakshi_mu_tau_30_1_bakshiSkew_tau_30_1,bakshi_mu_tau_30_1_bakshiSkew_tau_30_2,bakshi_mu_tau_30_1_bakshiSkew_tau_30_3,bakshi_mu_tau_30_1_bakshiSkew_tau_30_4,bakshi_mu_tau_30_2_bakshiSkew_tau_30_1,bakshi_mu_tau_30_2_bakshiSkew_tau_30_2,bakshi_mu_tau_30_2_bakshiSkew_tau_30_3,bakshi_mu_tau_30_2_bakshiSkew_tau_30_4,bakshi_mu_tau_30_3_bakshiSkew_tau_30_1,bakshi_mu_tau_30_3_bakshiSkew_tau_30_2,bakshi_mu_tau_30_3_bakshiSkew_tau_30_3,bakshi_mu_tau_30_3_bakshiSkew_tau_30_4,bakshi_mu_tau_30_4_bakshiSkew_tau_30_1,bakshi_mu_tau_30_4_bakshiSkew_tau_30_2,bakshi_mu_tau_30_4_bakshiSkew_tau_30_3,bakshi_mu_tau_30_4_bakshiSkew_tau_30_4,bakshi_mu_tau_30_bakshiSkew_tau_30_TopMinusBottom
0,2005-01-03,0.014557,-0.097570,-0.067442,-0.069036,-0.004988,-0.013442,-0.054180,-0.030646,0.004835,0.006419,-0.005188,-0.024909,-0.004749,0.007448,-0.017283,-0.013347,-0.027904
1,2005-02-01,0.064044,0.017657,0.034355,-0.007216,-0.014957,0.014362,-0.003498,0.028869,0.004443,0.010600,0.032013,0.013065,-0.013403,-0.015846,0.081034,-0.011632,-0.075676
2,2005-03-01,-0.047904,-0.050101,-0.078138,-0.041398,-0.029838,-0.010563,-0.033462,-0.036154,-0.111764,-0.024755,-0.007940,-0.035110,-0.026169,-0.013208,-0.055001,0.013295,0.061199
3,2005-04-01,-0.006244,-0.057019,-0.090024,-0.049262,0.002136,-0.055741,-0.026799,-0.013119,-0.019444,-0.042256,-0.023198,-0.038270,0.022854,0.030223,-0.040048,-0.042983,-0.036739
4,2005-05-02,0.055101,0.116600,0.090539,0.041443,0.014080,0.071264,0.038032,0.035370,0.026559,0.051705,0.065560,0.022595,0.007912,0.021297,-0.002562,0.001734,-0.053368
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,2022-08-01,-0.021591,-0.029811,0.056026,-0.037229,-0.027249,-0.030040,-0.021691,-0.039922,-0.012240,-0.020562,-0.019073,-0.024996,-0.026336,-0.014979,-0.030338,-0.049618,-0.028027
212,2022-09-01,-0.056777,-0.120045,-0.116139,-0.064831,-0.112326,-0.127377,-0.114839,-0.093807,-0.106755,-0.076222,-0.097633,-0.095791,-0.069573,-0.091239,-0.078295,-0.084220,-0.027443
213,2022-10-03,-0.030545,0.073249,-0.006974,0.061925,0.037608,-0.011428,0.091753,0.046716,0.036855,0.042613,0.053671,0.049109,0.080634,0.080743,0.031920,0.018973,0.049518
214,2022-11-01,-0.093573,0.048562,0.071951,0.159309,0.063550,0.056186,0.082015,0.016160,0.024028,0.060583,0.100179,0.101148,0.049366,0.054494,0.055516,0.061366,0.154940
215,2022-12-01,-0.073114,-0.101200,-0.153104,-0.110965,-0.061532,-0.104500,-0.058515,-0.050206,-0.036147,-0.076643,-0.062923,-0.037637,-0.024726,-0.031145,-0.033392,-0.031700,0.041413

In [5]:
df2 = pd.read_parquet("solution/PortfoliosOutcomePlusDiffTest.parquet")
df2

                                         Average    StdErr    t-stat   p-value
bakshi_mu_tau_30_1_bakshiSkew_tau_30_1  0.001200  0.006176  0.147274  0.882916
bakshi_mu_tau_30_1_bakshiSkew_tau_30_2  0.008370  0.006157  1.323490  0.185673
bakshi_mu_tau_30_1_bakshiSkew_tau_30_3  0.008362  0.006295  1.215040  0.224351
bakshi_mu_tau_30_1_bakshiSkew_tau_30_4  0.004236  0.007185  0.577239  0.563778
bakshi_mu_tau_30_2_bakshiSkew_tau_30_1  0.004739  0.004283  1.126594  0.259914
bakshi_mu_tau_30_2_bakshiSkew_tau_30_2  0.004225  0.004539  0.919257  0.357961
bakshi_mu_tau_30_2_bakshiSkew_tau_30_3  0.006581  0.004586  1.482076  0.138320
bakshi_mu_tau_30_2_bakshiSkew_tau_30_4  0.007370  0.004445  1.761637  0.078131
bakshi_mu_tau_30_3_bakshiSkew_tau_30_1  0.006105  0.003747  1.513431  0.130170
bakshi_mu_tau_30_3_bakshiSkew_tau_30_2  0.007569  0.003830  2.128137  0.033326
bakshi_mu_tau_30_3_bakshiSkew_tau_30_3  0.007775  0.003681  2.217158  0.026612
bakshi_mu_tau_30_3_bakshiSkew_tau_30_4  0.007795  0.003629  2.023630  0.043008
bakshi_mu_tau_30_4_bakshiSkew_tau_30_1  0.004234  0.002708  1.486583  0.137125
bakshi_mu_tau_30_4_bakshiSkew_tau_30_2  0.008028  0.002801  3.088202  0.002014
bakshi_mu_tau_30_4_bakshiSkew_tau_30_3  0.007185  0.002798  3.043268  0.002340
bakshi_mu_tau_30_4_bakshiSkew_tau_30_4  0.006648  0.002975  2.353979  0.018574
Difference in differences              -0.000623  0.004195 -0.150333  0.880502

In [3]:
df2

,date,bakshi_mu_tau_30_1_bakshiSkew_tau_30_1,bakshi_mu_tau_30_1_bakshiSkew_tau_30_2,bakshi_mu_tau_30_1_bakshiSkew_tau_30_3,bakshi_mu_tau_30_1_bakshiSkew_tau_30_4,bakshi_mu_tau_30_2_bakshiSkew_tau_30_1,bakshi_mu_tau_30_2_bakshiSkew_tau_30_2,bakshi_mu_tau_30_2_bakshiSkew_tau_30_3,bakshi_mu_tau_30_2_bakshiSkew_tau_30_4,bakshi_mu_tau_30_3_bakshiSkew_tau_30_1,bakshi_mu_tau_30_3_bakshiSkew_tau_30_2,bakshi_mu_tau_30_3_bakshiSkew_tau_30_3,bakshi_mu_tau_30_3_bakshiSkew_tau_30_4,bakshi_mu_tau_30_4_bakshiSkew_tau_30_1,bakshi_mu_tau_30_4_bakshiSkew_tau_30_2,bakshi_mu_tau_30_4_bakshiSkew_tau_30_3,bakshi_mu_tau_30_4_bakshiSkew_tau_30_4,Difference in differences
0,2005-01-03,0.014557,-0.097570,-0.067442,-0.069036,-0.004988,-0.013442,-0.054180,-0.030646,0.004835,0.006419,-0.005188,-0.024909,-0.004749,0.007448,-0.017283,-0.013347,0.074995
1,2005-02-01,0.064044,0.017657,0.034355,-0.007216,-0.014957,0.014362,-0.003498,0.028869,0.004443,0.010600,0.032013,0.013065,-0.013403,-0.015846,0.081034,-0.011632,0.073031
2,2005-03-01,-0.047904,-0.050101,-0.078138,-0.041398,-0.029838,-0.010563,-0.033462,-0.036154,-0.111764,-0.024755,-0.007940,-0.035110,-0.026169,-0.013208,-0.055001,0.013295,0.032957
3,2005-04-01,-0.006244,-0.057019,-0.090024,-0.049262,0.002136,-0.055741,-0.026799,-0.013119,-0.019444,-0.042256,-0.023198,-0.038270,0.022854,0.030223,-0.040048,-0.042983,-0.022819
4,2005-05-02,0.055101,0.116600,0.090539,0.041443,0.014080,0.071264,0.038032,0.035370,0.026559,0.051705,0.065560,0.022595,0.007912,0.021297,-0.002562,0.001734,0.007479
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,2022-08-01,-0.021591,-0.029811,0.056026,-0.037229,-0.027249,-0.030040,-0.021691,-0.039922,-0.012240,-0.020562,-0.019073,-0.024996,-0.026336,-0.014979,-0.030338,-0.049618,-0.007643
212,2022-09-01,-0.056777,-0.120045,-0.116139,-0.064831,-0.112326,-0.127377,-0.114839,-0.093807,-0.106755,-0.076222,-0.097633,-0.095791,-0.069573,-0.091239,-0.078295,-0.084220,-0.006592
213,2022-10-03,-0.030545,0.073249,-0.006974,0.061925,0.037608,-0.011428,0.091753,0.046716,0.036855,0.042613,0.053671,0.049109,0.080634,0.080743,0.031920,0.018973,-0.154129
214,2022-11-01,-0.093573,0.048562,0.071951,0.159309,0.063550,0.056186,0.082015,0.016160,0.024028,0.060583,0.100179,0.101148,0.049366,0.054494,0.055516,0.061366,-0.240882
215,2022-12-01,-0.073114,-0.101200,-0.153104,-0.110965,-0.061532,-0.104500,-0.058515,-0.050206,-0.036147,-0.076643,-0.062923,-0.037637,-0.024726,-0.031145,-0.033392,-0.031700,0.030877