In [20]:
import pandas as pd
import numpy as np
from datetime import time
import statsmodels.api as sm
import datetime as dt
start_date = "2005-03-01"
end_date = "2006-03-01"
df = pd.read_csv('data/SPY_15min_2002-01_to_2006-08.csv')
df2 = pd.read_csv('data/SPY_15min_2020-01_to_2022-01.csv')


#df['datetime'] = df['datetime'].dt.tz_localize('US/Eastern')
df['datetime'] = pd.to_datetime(df['Unnamed: 0'], utc=True)
print(df['Unnamed: 0'].head())
print(df['Unnamed: 0'].dtype)


df.set_index('datetime', inplace=True)
df.index = pd.DatetimeIndex(df.index)  # This ensures time-aware index
df = df.asfreq('15min')  # Ensure the index is at 15-minute frequency
df.index = df.index.tz_convert("Europe/Berlin")  # Convert to CET timezone
df = df.between_time("15:30", "22:00")
df = df[df.index.weekday < 5] # Keep only Monday (0) through Friday (4)

df["y^2"] = (df["close"].apply(lambda x: np.log(x)).diff()) ** 2
df = df.loc[pd.Timestamp(start_date).tz_localize("Europe/Berlin"):pd.Timestamp(end_date).tz_localize("Europe/Berlin")]

df.drop(columns=['Unnamed: 0'], inplace=True)
df.interpolate(method='time', inplace=True)


df["day_of_week"] = df.index.dayofweek
df["hour_of_day"] = df.index.hour

day_dummies = pd.get_dummies(df["day_of_week"], prefix="day", drop_first=True)
hour_dummies = pd.get_dummies(df["hour_of_day"], prefix="hour", drop_first=True)




df = pd.concat([df, day_dummies, hour_dummies], axis=1)
df

0    2002-01-02 09:30:00-05:00
1    2002-01-02 09:45:00-05:00
2    2002-01-02 10:00:00-05:00
3    2002-01-02 10:15:00-05:00
4    2002-01-02 10:30:00-05:00
Name: Unnamed: 0, dtype: object
object

,open,high,low,close,volume,y^2,day_of_week,hour_of_day,day_1,day_2,day_3,day_4,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22
datetime,,,,,,,,,,,,,,,,,,,
2005-03-01 15:30:00+01:00,83.1154,83.4113,83.1154,83.3769,3869200.0,1.779731e-05,1,15,True,False,False,False,False,False,False,False,False,False,False
2005-03-01 15:45:00+01:00,83.3769,83.4044,83.2805,83.3494,2046100.0,1.088221e-07,1,15,True,False,False,False,False,False,False,False,False,False,False
2005-03-01 16:00:00+01:00,83.3494,83.5971,83.2874,83.4870,5279800.0,2.720918e-06,1,16,True,False,False,False,True,False,False,False,False,False,False
2005-03-01 16:15:00+01:00,83.4870,83.5145,83.4044,83.4113,2816800.0,8.229017e-07,1,16,True,False,False,False,True,False,False,False,False,False,False
2005-03-01 16:30:00+01:00,83.4113,83.5489,83.3906,83.4870,1562300.0,8.229017e-07,1,16,True,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2006-02-28 21:00:00+01:00,89.8593,89.9154,89.7263,89.7543,3240400.0,1.190879e-06,1,21,True,False,False,False,False,False,False,False,False,True,False
2006-02-28 21:15:00+01:00,89.7543,89.9154,89.7473,89.9014,1836600.0,2.681659e-06,1,21,True,False,False,False,False,False,False,False,False,True,False
2006-02-28 21:30:00+01:00,89.9014,89.9854,89.8453,89.9644,1822900.0,4.907315e-07,1,21,True,False,False,False,False,False,False,False,False,True,False
2006-02-28 21:45:00+01:00,89.9714,89.9714,89.7963,89.8103,4144300.0,2.939059e-06,1,21,True,False,False,False,False,False,False,False,False,True,False
2006-02-28 22:00:00+01:00,89.8033,89.8733,89.7823,89.8243,1961900.0,2.429607e-08,1,22,True,False,False,False,False,False,False,False,False,False,True

In [56]:
#todo add overnight & over weekend dummmies
def safe_add(column: pd.Series, value: int): # Expects a datetimeIndex
    if not pd.api.types.is_datetime64_any_dtype(column):
        raise TypeError("Excpected a Series with DatetimeIndex.")
    # Check if the index is timezone-aware
    if column.dt.tz is None:
        raise ValueError("DatetimeIndex must be timezone-aware.")
    # Cast to ET timezone for timezone aware consistency
    column = column.dt.tz_convert("America/New_York")
    # Check whether value is outside of market open hours
    hypothetical_values = column + pd.Timedelta(minutes=value)

    mask_before_open = (hypothetical_values.dt.time < dt.time(9,30))
    mask_during_open = (dt.time(9,30) <= hypothetical_values.dt.time) & (hypothetical_values.dt.time <= dt.time(16,0))
    mask_after_open = (hypothetical_values.dt.time > dt.time(16,0))

    date_of_action = column.dt.normalize() # Extract date and set hours to 0:00
    output = column.copy()
    output[mask_during_open] = output[mask_during_open] + pd.Timedelta(minutes=value)
    if value >= 0: # Safe add
        output[mask_before_open] = date_of_action[mask_before_open] + pd.Timedelta(hours=9, minutes=30) + pd.Timedelta(minutes=value)
        output[mask_after_open] = date_of_action[mask_after_open] + pd.Timedelta(days=1) + pd.Timedelta(hours=9, minutes=30) + pd.Timedelta(minutes=value)
    else: # Safe subtract
        #todo check what happens when input to timedelta is negative
        output[mask_before_open] = date_of_action[mask_before_open] - pd.Timedelta(days=1) + pd.Timedelta(hours=16) + pd.Timedelta(minutes=value)
        output[mask_after_open] = date_of_action[mask_after_open] + pd.Timedelta(hours=16, minutes=value)

    return output # Caution: returns series with ET timezone


df_news = pd.read_csv('data/WhatMovesMarkets_eventdatabase.csv')
df_news["eventstart_CET"] = pd.to_datetime(df_news["eventstart_CET"], format="%d.%m.%Y %H:%M:%S").dt.tz_localize("Etc/GMT-1")  # Ensure correct timezone
df_news["eventend_CET"] = pd.to_datetime(df_news["eventend_CET"], format="%d.%m.%Y %H:%M:%S").dt.tz_localize("Etc/GMT-1")  # Ensure correct timezone
#df_news["eventstart_CET"] = df_news["eventstart_CET"].dt.floor("15min")  # Optional: Round down to the nearest 15 minutes (not mentioned in paper)

# Correct time window creation according to paper

event_end_mask = df_news["eventend_CET"].notna()

# Only assign to rows where event_end_mask is True
df_news.loc[event_end_mask, "window_start"] = (
    safe_add(df_news.loc[event_end_mask, "eventstart_CET"], -20)
    .dt.tz_convert("Etc/GMT-1")
)

df_news.loc[event_end_mask, "window_end"] = (
    safe_add(df_news.loc[event_end_mask, "eventend_CET"], 20)
    .dt.tz_convert("Etc/GMT-1")
)

# Only assign to rows where event_end_mask is False
df_news.loc[~event_end_mask, "window_start"] = (
    safe_add(df_news.loc[~event_end_mask, "eventstart_CET"], -15)
    .dt.tz_convert("Etc/GMT-1")
)

df_news.loc[~event_end_mask, "window_end"] = (
    safe_add(df_news.loc[~event_end_mask, "eventstart_CET"], 30)
    .dt.tz_convert("Etc/GMT-1")
)


df_news

,eventstart,eventend,name,type,subtype,subsubtype,description,source,scheduled,eventstart_CET,eventend_CET,window_start,window_end
0,01.03.2002 01:00:00,NaT,FI Consumer Confidence,Macro Release,FI,Consumer Confidence,NaN,Bloomberg,1,2002-03-01 07:00:00+01:00,NaT,2002-02-28 21:45:00+01:00,2002-03-01 16:00:00+01:00
1,01.03.2002 01:30:00,NaT,CH CPI,Macro Release,CH,CPI,NaN,Bloomberg,1,2002-03-01 07:30:00+01:00,NaT,2002-02-28 21:45:00+01:00,2002-03-01 16:00:00+01:00
2,01.03.2002 03:00:00,NaT,IT CPI,Macro Release,IT,CPI,NaN,Bloomberg,1,2002-03-01 09:00:00+01:00,NaT,2002-02-28 21:45:00+01:00,2002-03-01 16:00:00+01:00
3,01.03.2002 04:30:00,NaT,UK Monetary Aggregates,Macro Release,UK,Monetary Aggregates,NaN,Bloomberg,1,2002-03-01 10:30:00+01:00,NaT,2002-02-28 21:45:00+01:00,2002-03-01 16:00:00+01:00
4,01.03.2002 06:00:00,NaT,EA Retail Sales & EA Retail Trade,Macro Release,EA,Retail Sales & EA Retail Trade,NaN,Bloomberg,1,2002-03-01 12:00:00+01:00,NaT,2002-02-28 21:45:00+01:00,2002-03-01 16:00:00+01:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
51566,31.08.2020 11:35:00,NaT,US Auction Result Bill,Auction,US Result,Bill,CUSIP 9127964F3,https://www.treasurydirect.gov/instit/annceres...,1,2020-08-31 17:30:00+01:00,NaT,2020-08-31 17:15:00+01:00,2020-08-31 18:00:00+01:00
51567,31.08.2020 11:35:00,NaT,US Auction Result Bill,Auction,US Result,Bill,CUSIP 912796TU3,https://www.treasurydirect.gov/instit/annceres...,1,2020-08-31 17:30:00+01:00,NaT,2020-08-31 17:15:00+01:00,2020-08-31 18:00:00+01:00
51568,31.08.2020 20:00:00,NaT,IE Investec Manufacturing PMI,Macro Release,IE,Investec Manufacturing PMI,NaN,Bloomberg,1,2020-09-01 02:00:00+01:00,NaT,2020-08-31 20:45:00+01:00,2020-09-01 15:00:00+01:00
51569,31.08.2020 20:30:00,NaT,JP Markit/JMMA Manufacturing PMI,Macro Release,JP,Markit/JMMA Manufacturing PMI,NaN,Bloomberg,1,2020-09-01 02:30:00+01:00,NaT,2020-08-31 20:45:00+01:00,2020-09-01 15:00:00+01:00
51570,31.08.2020 21:45:00,NaT,CN HSBC Manufacturing PMI,Macro Release,CN,HSBC Manufacturing PMI,NaN,Bloomberg,1,2020-09-01 03:45:00+01:00,NaT,2020-08-31 20:45:00+01:00,2020-09-01 15:00:00+01:00

In [3]:
#todo make this faster
print(f"creating {len(df_news["subsubtype"].unique())} event dummie variables")
dummies = {}
for subsubtype, df_type in df_news.groupby("subsubtype"):
    mask = pd.Series(False, index=df.index)
    for _, row in df_type.iterrows():
        mask |= (df.index >= row["window_start"]) & (df.index < row["window_end"])
        dummies[f"D_{subsubtype}"] = mask

df = pd.concat([df, pd.DataFrame(dummies)], axis=1)
df

creating 128 event dummie variables
7047

,open,high,low,close,volume,y^2,day_of_week,hour_of_day,day_1,day_2,...,D_Trade & Current Account Balance,D_Trade Balance,D_Trade Balance Non-Eu (Euros),D_Trade Data (CNY),D_Ulster Bank Construction PMI,D_Unemployment Net,D_Unemployment Rate,D_University of Michigan Surveys,D_Weekly Financial Statement,D_Wholesale Price Index
datetime,,,,,,,,,,,,,,,,,,,,,
2005-03-01 15:30:00+01:00,83.1154,83.4113,83.1154,83.3769,3869200.0,1.779731e-05,1,15,True,False,...,False,False,False,False,False,False,False,False,False,False
2005-03-01 15:45:00+01:00,83.3769,83.4044,83.2805,83.3494,2046100.0,1.088221e-07,1,15,True,False,...,False,False,False,False,False,False,False,False,False,False
2005-03-01 16:00:00+01:00,83.3494,83.5971,83.2874,83.4870,5279800.0,2.720918e-06,1,16,True,False,...,False,False,False,False,False,False,False,False,False,False
2005-03-01 16:15:00+01:00,83.4870,83.5145,83.4044,83.4113,2816800.0,8.229017e-07,1,16,True,False,...,False,False,False,False,False,False,False,False,False,False
2005-03-01 16:30:00+01:00,83.4113,83.5489,83.3906,83.4870,1562300.0,8.229017e-07,1,16,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2006-02-28 21:00:00+01:00,89.8593,89.9154,89.7263,89.7543,3240400.0,1.190879e-06,1,21,True,False,...,False,False,False,False,False,False,False,False,False,False
2006-02-28 21:15:00+01:00,89.7543,89.9154,89.7473,89.9014,1836600.0,2.681659e-06,1,21,True,False,...,False,False,False,False,False,False,False,False,False,False
2006-02-28 21:30:00+01:00,89.9014,89.9854,89.8453,89.9644,1822900.0,4.907315e-07,1,21,True,False,...,False,False,False,False,False,False,False,False,False,False
2006-02-28 21:45:00+01:00,89.9714,89.9714,89.7963,89.8103,4144300.0,2.939059e-06,1,21,True,False,...,False,False,False,False,False,False,False,False,False,False
2006-02-28 22:00:00+01:00,89.8033,89.8733,89.7823,89.8243,1961900.0,2.429607e-08,1,22,True,False,...,False,False,False,False,False,False,False,False,False,False

In [16]:
# Regression
k = 4

fixed_effects = pd.concat([day_dummies, hour_dummies], axis=1).astype(float)
event_dummies = pd.DataFrame(dummies).astype(float)
lagged_variance = df['y^2'].rolling(window=k).sum()  # assuming k 15-min intervals according to paper




x = pd.concat([event_dummies, fixed_effects, lagged_variance], axis=1)
x.dropna(inplace=True) #drops first 3 rows due to rolling window
x = sm.add_constant(x)
y = df["y^2"].iloc[3:].astype(float)
#model = sm.OLS(y, x).fit(cov_type='cluster', cov_kwds={'groups': df.index.date})
model = sm.OLS(y, x).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    y^2   R-squared:                       0.320
Model:                            OLS   Adj. R-squared:                  0.316
Method:                 Least Squares   F-statistic:                     82.24
Date:                Thu, 10 Jul 2025   Prob (F-statistic):               0.00
Time:                        10:51:12   Log-Likelihood:                 80485.
No. Observations:                7044   AIC:                        -1.609e+05
Df Residuals:                    7003   BIC:                        -1.606e+05
Df Model:                          40
Covariance Type:            nonrobust
=========================================================================================================================
                                                            coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------
const                                                  1.594e-06   1.41e-07     11.284      0.000    1.32e-06    1.87e-06
D_ADP Employment Change                                 6.29e-14   1.27e-15     49.705      0.000    6.04e-14    6.54e-14
D_Accounts                                             -5.61e-14   1.13e-15    -49.705      0.000   -5.83e-14   -5.39e-14
D_Actual FDI & CN Contract FDI Cumulative               2.88e-14   5.79e-16     49.705      0.000    2.77e-14    2.99e-14
D_Ad Hoc Press Release                                 4.565e-14   9.18e-16     49.705      0.000    4.38e-14    4.74e-14
D_Asset Purchase Programmes                           -1.855e-14   3.73e-16    -49.705      0.000   -1.93e-14   -1.78e-14
D_BRC Sales Like-For-Like                              2.949e-14   5.93e-16     49.705      0.000    2.83e-14    3.07e-14
D_BRC Shop Price Index                                 6.401e-14   1.29e-15     49.705      0.000    6.15e-14    6.65e-14
D_Bank Lending and Monetary Aggregates                 6.882e-14   1.38e-15     49.705      0.000    6.61e-14    7.15e-14
D_Bankruptcies                                         5.575e-14   1.12e-15     49.705      0.000    5.36e-14    5.79e-14
D_Beige Book                                           8.801e-08   5.47e-07      0.161      0.872   -9.84e-07    1.16e-06
D_Bill                                                  5.79e-08   1.14e-07      0.506      0.613   -1.66e-07    2.82e-07
D_Bond                                                 4.352e-08   6.87e-07      0.063      0.949    -1.3e-06    1.39e-06
D_Bond or Note                                         6.203e-14   1.25e-15     49.705      0.000    5.96e-14    6.45e-14
D_Budget Balance                                      -1.906e-07   6.58e-07     -0.290      0.772   -1.48e-06     1.1e-06
D_Building Permits & US Housing Starts                 2.821e-14   5.68e-16     49.705      0.000    2.71e-14    2.93e-14
D_Business and Consumer Confidence                     3.823e-14   7.69e-16     49.705      0.000    3.67e-14    3.97e-14
D_CPI                                                  3.063e-14   6.16e-16     49.705      0.000    2.94e-14    3.18e-14
D_CPI & GR CPI EU Harmonized                            8.83e-14   1.78e-15     49.705      0.000    8.48e-14    9.18e-14
D_CPI Hesse                                            1.498e-13   3.01e-15     49.705      0.000    1.44e-13    1.56e-13
D_CPI and Earnings Data                               -4.703e-14   9.46e-16    -49.705      0.000   -4.89e-14   -4.52e-14
D_CPI and Wages                                       -4.472e-14      9e-16    -49.705      0.000   -4.65e-14    -4.3e-14
D_Cabinet Office Indices                               1.594e-13   3.21e-15     49.705      0.000    1.53e-13    1.66e-13
D_Capacity Utilization & JP Industrial Production      1.786e-13   3.59e-15     49.705      0.000    1.72e-13    1.86e-13
D_Car Prod.                                            1.834e-13   3.69e-15     49.705      0.000    1.76e-13    1.91e-13
D_Car Registrations                                   -3.867e-14   7.78e-16    -49.705      0.000   -4.02e-14   -3.71e-14
D_Car Sales                                            2.109e-14   4.24e-16     49.705      0.000    2.03e-14    2.19e-14
D_Chicago Purchasing Manager                          -1.232e-06   5.13e-07     -2.402      0.016   -2.24e-06   -2.26e-07
D_Conference Board Indices                             2.873e-08   4.83e-07      0.059      0.953   -9.18e-07    9.76e-07
D_Consumer Confidence                                  3.704e-14   7.45e-16     49.705      0.000    3.56e-14    3.85e-14
D_Current Account                                      8.452e-14    1.7e-15     49.705      0.000    8.12e-14    8.79e-14
D_Current Account Balance                             -1.012e-13   2.04e-15    -49.705      0.000   -1.05e-13   -9.72e-14
D_Discount Rate Minutes                                4.036e-08   5.15e-07      0.078      0.938   -9.69e-07    1.05e-06
D_Durable Goods                                       -1.212e-06   4.57e-07     -2.651      0.008   -2.11e-06   -3.16e-07
D_Earnings Data                                       -5.182e-14   1.04e-15    -49.705      0.000   -5.39e-14   -4.98e-14
D_Eco Watchters Survey                                 6.224e-15   1.25e-16     49.705      0.000    5.98e-15    6.47e-15
D_Economic Bulletin                                    3.239e-14   6.52e-16     49.705      0.000    3.11e-14    3.37e-14
D_Empire Manufacturing                                -4.407e-15   8.87e-17    -49.705      0.000   -4.58e-15   -4.23e-15
D_Employment                                          -7.176e-18   1.44e-19    -49.705      0.000   -7.46e-18   -6.89e-18
D_Employment Cost Index                               -6.981e-19   1.41e-20    -49.681      0.000   -7.26e-19   -6.71e-19
D_Employment Report                                   -1.336e-07   1.53e-06     -0.087      0.931   -3.14e-06    2.87e-06
D_Existing Home Sales                                  1.357e-08   4.59e-07      0.030      0.976   -8.86e-07    9.14e-07
D_FDI                                                          0          0        nan        nan           0           0
D_Factory Orders                                       1.035e-06   1.53e-06      0.676      0.499   -1.97e-06    4.04e-06
D_Foreign Investment                                           0          0        nan        nan           0           0
D_Foreign Reserves                                             0          0        nan        nan           0           0
D_GDP                                                          0          0        nan        nan           0           0
D_GDP & NO GDP Mainland                                        0          0        nan        nan           0           0
D_GDP Components                                               0          0        nan        nan           0           0
D_GDP and Components                                           0          0        nan        nan           0           0
D_GDP and Other Macro Aggregates                               0          0        nan        nan           0           0
D_GDP, GDP Price Index, PCE                            1.653e-06   1.53e-06      1.079      0.281   -1.35e-06    4.66e-06
D_HSBC Composite PMI & CN HSBC Services PMI                    0          0        nan        nan           0           0
D_HSBC Manufacturing PMI                                       0          0        nan        nan           0           0
D_Halifax House Prices                                         0          0        nan        nan           0           0
D_Hometrack Housing Survey                                     0          0        nan        nan           0           0
D_House Price Index & FI House Prices                          0          0        nan        nan           0           0
D_Household Consumption                                        0          0        nan        nan           0           0
D_Household Spending & JP Overall Household Spending           0          0        nan        nan           0           0
D_Housing Loans                                                0          0        nan        nan           0           0
D_Housing Permits & FR Housing Starts                          0          0        nan        nan           0           0
D_IFO Survey                                                   0          0        nan        nan           0           0
D_INE House Price Index                                        0          0        nan        nan           0           0
D_ISM Non-Manufacturing                               -5.539e-07   4.57e-07     -1.211      0.226   -1.45e-06    3.43e-07
D_ISM Releases                                        -1.966e-06   4.62e-07     -4.260      0.000   -2.87e-06   -1.06e-06
D_Import Price Index                                           0          0        nan        nan           0           0
D_Ind Prod Manufacturing & NO Industrial Production            0          0        nan        nan           0           0
D_Industrial Production                                9.633e-08   6.04e-07      0.159      0.873   -1.09e-06    1.28e-06
D_Industrial Production & FR Manufacturing Production          0          0        nan        nan           0           0
D_Industrial Production & UK Manufacturing Production          0          0        nan        nan           0           0
D_Industrial Production and Orders                             0          0        nan        nan           0           0
D_Industrial Profits                                           0          0        nan        nan           0           0
D_Industrial Sales & NL Manufacturing Production               0          0        nan        nan           0           0
D_Inflation Reports                                            0          0        nan        nan           0           0
D_Investec Manufacturing PMI                                   0          0        nan        nan           0           0
D_Jobless Claims                                      -8.997e-07   1.53e-06     -0.587      0.557    -3.9e-06     2.1e-06
D_Leading Index                                       -8.061e-08   4.52e-07     -0.178      0.858   -9.67e-07    8.05e-07
D_M2 and M3                                                    0          0        nan        nan           0           0
D_MRO                                                          0          0        nan        nan           0           0
D_Machine Orders                                               0          0        nan        nan           0           0
D_Machine Tool Orders                                          0          0        nan        nan           0           0
D_Manpower Survey                                              0          0        nan        nan           0           0
D_Manufacturing and Business Confidence                        0          0        nan        nan           0           0
D_Markit Composite PMI & ES Markit Services PMI                0          0        nan        nan           0           0
D_Markit Services PMI & JP Markit/JMMA Composite PMI           0          0        nan        nan           0           0
D_Markit/JMMA Manufacturing PMI                                0          0        nan        nan           0           0
D_Minutes                                              6.839e-07   5.47e-07      1.250      0.211   -3.88e-07    1.76e-06
D_Monetary Aggregates                                          0          0        nan        nan           0           0
D_Monetetary Aggregates                                        0          0        nan        nan           0           0
D_Monthly Report                                               0          0        nan        nan           0           0
D_New Home Sales                                       -7.91e-07   4.61e-07     -1.718      0.086   -1.69e-06    1.12e-07
D_Nonfarm Productivity & US Unit Labor Costs                   0          0        nan        nan           0           0
D_Note                                                 2.134e-07   1.99e-07      1.070      0.285   -1.78e-07    6.04e-07
D_Official Reserve Assets                                      0          0        nan        nan           0           0
D_Official Reserves                                            0          0        nan        nan           0           0
D_Official Reserves Changes                                    0          0        nan        nan           0           0
D_PMI                                                          0          0        nan        nan           0           0
D_PPI                                                  2.713e-07   7.04e-07      0.385      0.700   -1.11e-06    1.65e-06
D_PPI Services                                                 0          0        nan        nan           0           0
D_Press Conference                                             0          0        nan        nan           0           0
D_Press Release                                        1.066e-06   5.49e-07      1.942      0.052   -1.03e-08    2.14e-06
D_Price Indices                                                0          0        nan        nan           0           0
D_Producer, Import Prices                                      0          0        nan        nan           0           0
D_Production and Capacity Utilization                          0          0        nan        nan           0           0
D_Quarterly Bulletin                                           0          0        nan        nan           0           0
D_Retail Sales                                                 0          0        nan        nan           0           0
D_Retail Sales & EA Retail Trade                               0          0        nan        nan           0           0
D_Retail Sales & FI Retail Sales Volume                        0          0        nan        nan           0           0
D_Rightmove House Prices                                       0          0        nan        nan           0           0
D_Sentix Investor Confidence                                   0          0        nan        nan           0           0
D_Speech by Chair                                     -5.737e-07   4.91e-07     -1.169      0.243   -1.54e-06    3.89e-07
D_Speech by FOMC member                                 1.01e-07   3.17e-07      0.319      0.750    -5.2e-07    7.22e-07
D_Speech by GC member                                  7.137e-08   3.57e-07      0.200      0.841   -6.28e-07    7.71e-07
D_Speech by Governor                                           0          0        nan        nan           0           0
D_Speech by President                                  1.262e-07   4.95e-07      0.255      0.799   -8.44e-07     1.1e-06
D_Summary of Opinions                                          0          0        nan        nan           0           0
D_Tertiary Industry Index                                      0          0        nan        nan           0           0
D_Tokyo Condominium Sales                                      0          0        nan        nan           0           0
D_Trade & Current Account Balance                              0          0        nan        nan           0           0
D_Trade Balance                                                0          0        nan        nan           0           0
D_Trade Balance Non-Eu (Euros)                                 0          0        nan        nan           0           0
D_Trade Data (CNY)                                             0          0        nan        nan           0           0
D_Ulster Bank Construction PMI                                 0          0        nan        nan           0           0
D_Unemployment Net                                             0          0        nan        nan           0           0
D_Unemployment Rate                                    -9.74e-08    5.9e-07     -0.165      0.869   -1.25e-06    1.06e-06
D_University of Michigan Surveys                        4.42e-07   3.27e-07      1.350      0.177      -2e-07    1.08e-06
D_Weekly Financial Statement                                   0          0        nan        nan           0           0
D_Wholesale Price Index                                        0          0        nan        nan           0           0
day_1                                                  3.391e-09   1.02e-07      0.033      0.973   -1.96e-07    2.03e-07
day_2                                                  2.872e-09   1.03e-07      0.028      0.978   -1.98e-07    2.04e-07
day_3                                                  3.058e-08   1.01e-07      0.302      0.763   -1.68e-07    2.29e-07
day_4                                                   3.12e-08   1.05e-07      0.298      0.766   -1.74e-07    2.36e-07
hour_16                                               -2.168e-06   1.43e-07    -15.155      0.000   -2.45e-06   -1.89e-06
hour_17                                               -1.685e-06   1.48e-07    -11.423      0.000   -1.97e-06    -1.4e-06
hour_18                                               -1.651e-06   1.49e-07    -11.081      0.000   -1.94e-06   -1.36e-06
hour_19                                               -1.568e-06   1.49e-07    -10.555      0.000   -1.86e-06   -1.28e-06
hour_20                                               -1.519e-06   1.47e-07    -10.311      0.000   -1.81e-06   -1.23e-06
hour_21                                               -1.563e-06   1.46e-07    -10.714      0.000   -1.85e-06   -1.28e-06
hour_22                                               -1.836e-06   2.03e-07     -9.031      0.000   -2.23e-06   -1.44e-06
y^2                                                       0.2446      0.005     49.705      0.000       0.235       0.254
==============================================================================
Omnibus:                     7218.298   Durbin-Watson:                   2.247
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1403160.741
Skew:                           4.637   Prob(JB):                         0.00
Kurtosis:                      71.518   Cond. No.                     1.32e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.31e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.